### PR TITLE
Failure Notification Example Via Slack

### PR DESCRIPTION
**Pull request by xplrior**
This example workflow is to show how to set up a failure notification when the workflow fails. The example here will send a slack notification when the workflow exits with a failure.

### CODE REVIEW

**Comment by xplrior** [comment]
This is for https://github.com/codefresh-contrib/csdp01_git-source/issues/23

**Review by lrochette — CHANGES_REQUESTED** [review]
Checking with @eti-codefresh  if we really need a rbac.yaml as part of the sample

I ran the workflow and the log for slack-notification shows
```
time="2022-10-05T18:07:42.513Z" level=info msg="capturing logs" argo=true
Choose simple mode
Cant send notification to slack , error : no_service, check your SLACK_HOOK_URL
```

but the step did not fail. Is that something you can fix

Codefresh___Argo-hub_failure-notification-example_0_0_1-jjqpv

**Comment by lrochette** [comment]
Missing rbac.yaml as well

**Comment by xplrior** [comment]
@lrochette added the rbac.yaml for the workflow.

**Comment by lrochette** [comment]
> @lrochette that Slack URL you have provided is bad. It returns "no service" so the step is working correctly from what I am seeing.

yes I know the URL is wrong (it was decommissioned) but the step is green. This is the part that's weird as it makes me believe my alter was sent properly

**Review by lrochette — APPROVED** [review]

**Pull request merged**
